apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-app-lynceus-ai
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: app-lynceus-ai-credential
      hosts:
        - "app.lynceus.ai"
