---
apiVersion: v1
kind: Namespace
metadata:
  name: lcs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: lcs
  name: ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lcs
  name: ecr-renew
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: lcs
  name: ecr-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-renew
subjects:
  - kind: ServiceAccount
    name: ecr-renew
    namespace: lcs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: lcs
  name: ecr-renew
  labels:
    app: ecr-renew
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: ecr-renew
          containers:
            - name: ecr-renew
              image: nabsul/k8s-ecr-login-renew:v1.5
              env:
                - name: DOCKER_SECRET_NAME
                  value: ecr-docker-login
                - name: TARGET_NAMESPACE
                  value: lcs
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: ecr-renew-cred
                      key: REGION
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: ecr-renew-cred
                      key: ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ecr-renew-cred
                      key: SECRET
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: lcs
  name: ecr-renew-manual
spec:
    template:
      spec:
        restartPolicy: OnFailure
        serviceAccountName: ecr-renew
        containers:
          - name: ecr-renew
            image: nabsul/k8s-ecr-login-renew:v1.5
            env:
              - name: DOCKER_SECRET_NAME
                value: ecr-docker-login
              - name: TARGET_NAMESPACE
                value: lcs
              - name: AWS_REGION
                valueFrom:
                  secretKeyRef:
                    name: ecr-renew-cred
                    key: REGION
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: ecr-renew-cred
                    key: ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: ecr-renew-cred
                    key: SECRET
