apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: platform-docs
  namespace: lcs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform-docs
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (100m)
      targetAverageUtilization: 99
